server:
  AppVersion: 1.0.0
  Port: :6000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false
  MaxConnectionIdle: 5
  Timeout: 15
  MaxConnectionAge: 5
  Time: 120

Gateway:
  Port: :8000
  ServerAddress: localhost
  ServerPort: :6000

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

Database:
  DBType: mysql
  DBUser: go
  DBPass: go
  DBName: go
  DBHost: localhost
  DBPort: 3306

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

metrics:
  Url: 0.0.0.0:7070
  ServiceName: auth_microservice

jaeger:
  Host: localhost:6831
  ServiceName: Auth_GRPC
  LogSpans: false

Common:
  JWTSecret: 1234%^&*ukfykjSCFAVARBTSDN